# Cargar librerías necesarias
library(ggplot2)
library(nnet)  # Para la red neuronal
library(dplyr)

# Definir rango de valores para asegurar un gráfico cuadrado
set.seed(123)
n <- 20  # Número de puntos por clase

# Clase 0 (azul) en la parte superior izquierda de una frontera curva
x1_class0 <- runif(n, -3, 3)
x2_class0 <- runif(n, x1_class0^2 - 2, 3)  # Frontera cuadrática más suave
y_class0 <- rep(0, n)

# Clase 1 (rojo) en la parte inferior derecha
x1_class1 <- runif(n, -3, 3)
x2_class1 <- runif(n, -3, x1_class1^2 - 2)  # Frontera cuadrática más suave
y_class1 <- rep(1, n)

# Combinar los datos en un data frame
data <- data.frame(
  x1 = c(x1_class0, x1_class1),
  x2 = c(x2_class0, x2_class1),
  y = as.factor(c(y_class0, y_class1))
)

# Filtrar los datos para mantener dentro de los límites [-3, 3]
data <- data %>% filter(x1 >= -3 & x1 <= 3 & x2 >= -3 & x2 <= 3)

# Entrenar la red neuronal con nnet
nn_model <- nnet(y ~ x1 + x2, data = data, size = 5, maxit = 500, decay = 0.1)

# Crear una malla de puntos para visualizar la frontera de decisión
grid_size <- 300
x1_seq <- seq(-3, 3, length.out = grid_size)
x2_seq <- seq(-3, 3, length.out = grid_size)
grid <- expand.grid(x1 = x1_seq, x2 = x2_seq)

# Predecir las clases en la malla
grid$y_pred <- predict(nn_model, grid, type = "class")

# Graficar la frontera de decisión con ggplot2
plot <- ggplot(data, aes(x = x1, y = x2)) +
  geom_tile(data = grid, aes(fill = y_pred), alpha = 0.3) +  # Superficie de decisión
  geom_point(aes(color = y), size = 2) +  # Puntos de datos originales
  scale_fill_manual(values = c("blue", "red"), name = "Predicted Class") +
  scale_color_manual(values = c("blue", "red"), name = "Actual Class") +
  coord_fixed(xlim = c(-3, 3), ylim = c(-3, 3)) +  # Limitar el gráfico a [-3, 3]
  theme_minimal() +
  labs(#title = "Nonlinear Decision Boundary Generated by a Neural Network",
       x = "Feature 1",
       y = "Feature 2") +
  theme(legend.position = "right")

plot

ggsave(plot = plot, dpi = 600, filename = "nonlinear decision boundary NN.png")
